package nxu.it.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setSno(java.lang.String sno) {
		set("sno", sno);
	}
	
	public java.lang.String getSno() {
		return getStr("sno");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}
	
	public void setDepartmentId(java.lang.Integer departmentId) {
		set("department_id", departmentId);
	}
	
	public java.lang.Integer getDepartmentId() {
		return getInt("department_id");
	}
	
	public void setGrade(java.lang.Integer grade) {
		set("grade", grade);
	}
	
	public java.lang.Integer getGrade() {
		return getInt("grade");
	}
	
	public void setMajor(java.lang.String major) {
		set("major", major);
	}
	
	public java.lang.String getMajor() {
		return getStr("major");
	}
	
}

