package nxu.it.model;

import nxu.it.model.base.BasePost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Post extends BasePost<Post> {
	public static final Post dao = new Post();
}

